def name
  @name ||= "nuric"
end

def version
  @version ||= File.read('../VERSION').strip
end

def home
  @home ||= File.dirname(__FILE__)
end

def share_dir
  "#{home}/share"
end

def test_dir
  "#{home}/../test"
end

def bin_dir
  "#{home}/bin"
end

def lib_dir
  "#{home}/lib/nuric"
end

def ocaml_dir
  "#{home}/../ocaml"
end

def platform
  @platform ||= case RUBY_PLATFORM
    when /.*linux.*/
      'linux'
    when /.*darwin.*/
      'osx'
    when /.*(cygwin|mswin|mingw|bccwin|wince|emx).*/
      'win'
    else
      ''
    end
end

def testfiles
  File.read("#{home}/../test/good-test-files.txt").
    split("\n")
end

def gem_file
  @gem_file ||= "#{name}-#{version}.gem"
end

def nuric
  if platform
    "#{share_dir}/#{platform}/#{name}"
  else
    "#{share_dir}/#{name}"
  end
end

task :default => :build

task :build do
  # build
  Dir.chdir ocaml_dir
  sh 'make NATIVE=1 STACK_TRACE=0'
  FileUtils.mkdir "#{share_dir}/#{platform}" unless
    Dir.exist?("#{share_dir}/#{platform}")
  FileUtils.cp name, nuric

  # test
  Dir.chdir test_dir
  testfiles.each do |file|
  	sh "#{nuric} #{file} 1>/dev/null"
  end
  Dir.chdir "#{home}/test"

  Dir.chdir home
  sh "gem build #{name}.gemspec"
end

task :clean do
  FileUtils.rm nuric if File.exists?(nuric)
  FileUtils.rm gem_file if File.exists?(gem_file)
end
